name: Echo

on:
  workflow_dispatch:

jobs:
  git:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set the value in bash
        id: step_one
        run: |
          mkdir result
          git diff $(git tag --sort version:refname | tail -n 2 | head -n 1 ) documents/*.md  >> result/diff.diff

      - name: Archive Artifact 📮
        uses: actions/upload-artifact@master
        with:
          name: result
          path: result

  slack:
    name: Send Slack
    needs: git
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Download Artifact 📬
        uses: actions/download-artifact@master
        with:
          name: result
          path: result
      - name: Upload to slack step
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          path: result/diff.diff
          channel: development
