name: Echo

on:
  push:
    branches:
      - chore/echo
  workflow_dispatch:

jobs:
  git:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set the value in bash
        id: step_one
        run: |
          mkdir diff
          result=$(git diff origin/main) && echo $result >> diff/test.diff

      - name: Archive Artifact 📮
        uses: actions/upload-artifact@master
        with:
          name: diff
          path: diff

  deploy:
    name: Deploy
    needs: git
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Download Artifact 📬
        uses: actions/download-artifact@master
        with:
          name: diff
          path: diff
      - name: Upload to slack step
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          path: diff/test.diff
          channel: room-yanskun
