name: Echo

on:
  push:
    branches:
      - chore/echo
  workflow_dispatch:

jobs:
  git:
    name: Git
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.git_diff.outputs.diff }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: get_diff
        name: Get diff
        run: |
          echo "DIFF=$(git diff origin/main)"
          echo "diff=${DIFF}" >> $GITHUB_OUTPUT

  slack:
    name: Send Slack
    runs-on: ubuntu-latest
    needs: [git]
    env:
      DIFF: ${{ needs.git.outputs.diff }}
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "テストでーす"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": ":diff: \n ```${{ needs.git.outputs.diff }}```"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
