name: Echo

on:
  push:
    branches:
      - chore/echo
  workflow_dispatch:

jobs:
  echo:
    name: echo
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: get_diff
        name: Get diff
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          diff=$(git diff main)
          echo "body=$diff >> $GITHUB_OUTPUT"

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "テストでーす"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": ":diff: \n ```${{ steps.get_diff.outputs.body  }}```"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
