name: Echo

on:
  push:
    branches:
      - chore/echo
  workflow_dispatch:

jobs:
  git:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      diff: ${{ steps.echo.outputs.test }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set the value in bash
        id: step_one
        run: |
          diff=$(git diff)
          echo $diff >> diff/test.diff

      - name: Archive Artifact 📮
        uses: actions/upload-artifact@master
        with:
          name: diff
          path: diff

  deploy:
    name: Deploy
    needs: git
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Download Artifact 📬
        uses: actions/download-artifact@master
        with:
          name: diff
          path: diff
      - name: bash
        run: |
          ls .
  #   runs-on: ubuntu-latest
  #   needs: git
  #   steps:
  #   - run: echo ${{needs.git.outputs.diff}}

# jobs:
#   git:
#     name: Git
#     runs-on: ubuntu-latest
#     outputs:
#       diff: ${{ steps.git_diff.outputs.diff }}
#     steps:
#       - name: Check out code
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
#
#       - id: get_diff
#         name: Get diff
#         run: |
#           # echo "DIFF=$(git diff origin/main)"
#           # echo "diff=${DIFF}" >> $GITHUB_OUTPUT
#           echo "diff=hello" >> $GITHUB_OUTPUT
#
#   slack:
#     name: Send Slack
#     runs-on: ubuntu-latest
#     needs: git
#     # env:
#     #   DIFF: ${{ needs.git.outputs.diff }}
#     steps:
#       - name: echo
#         run: echo hoge ${{needs.git.outputs.diff}}
      # - name: Send custom JSON data to Slack workflow
      #   id: slack
      #   uses: slackapi/slack-github-action@v1.24.0
      #   with:
      #     payload: |
      #       {
      #         "blocks": [
      #           {
      #             "type": "section",
      #             "text": {
      #               "type": "mrkdwn",
      #               "text": "なんで動かないのかわからない"
      #             }
      #           },
      #           {
      #             "type": "context",
      #             "elements": [
      #               {
      #                 "type": "mrkdwn",
      #                 "text": ":diff: \n ```${DIFF}```"
      #               }
      #             ]
      #           }
      #         ]
      #       }
      #   env:
      #     SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
